name: Collect runner's stats

inputs:
  target_os:
    required: true
    type: string
  target_arch:
    required: true
    type: string
  cxx_compiler:
    required: true
    type: string
  build_config:
    required: true
    type: string

outputs:
  job_id:
    description: "Current job ID"
    value: ${{ steps.fetch_job_id.outputs.job_id }}
  cpu_count:
    description: "Runner's CPU count"
    value: ${{ steps.collect_stats.outputs.cpu_count }}
  ram_amount_mb:
    description: "Runner's RAM amount in megabytes"
    value: ${{ steps.collect_stats.outputs.ram_amount_mb }}

runs:
  using: composite
  steps:
    - name: Fetch job ID
      id: fetch_job_id
      shell: python3 fetch_job_id.py
      working-directory: ${{ github.action_path }}/../../../scripts/devops
      env:
        GITHUB_TOKEN: ${{ github.token }}
      run: ""

    - name: Collect sys stats
      id: collect_stats
      shell: python3 collect_runner_sys_stats.py
      working-directory: ${{ github.action_path }}/../../../scripts/devops
      env:
        TARGET_OS: ${{ inputs.target_os }}
        TARGET_ARCH: ${{ inputs.target_arch }}
        CXX_COMPILER: ${{ inputs.cxx_compiler }}
        BUILD_CONFIG: ${{ inputs.build_config }}
        STATS_FILE: "RunnerSysStats-${{ steps.fetch_job_id.outputs.job_id }}.json"
      run: ""

    - name: Upload sys stats
      uses: actions/upload-artifact@v4
      with:
        name: RunnerSysStats-${{ steps.fetch_job_id.outputs.job_id }}
        path: RunnerSysStats-${{ steps.fetch_job_id.outputs.job_id }}.json
        retention-days: 1
