name: Collect runner's stats

inputs:
  target_os:
    required: true
    type: string
  target_arch:
    required: true
    type: string
  cxx_compiler:
    required: true
    type: string
  build_config:
    required: true
    type: string

outputs:
  job_id:
    description: "Current job ID"
    value: ${{ steps.fetch_job_id.outputs.job_id }}
  cpu_count:
    description: "Runner's CPU count"
    value: ${{ steps.collect_stats.outputs.cpu_count }}
  ram_amount_mb:
    description: "Runner's RAM amount in megabytes"
    value: ${{ steps.collect_stats.outputs.ram_amount_mb }}

runs:
  using: composite
  steps:
    - name: Fetch job ID
      id: fetch_job_id
      shell: bash
      env:
        GITHUB_TOKEN: ${{ github.token }}
      run: |
        JOB_ID=$(python3 scripts/devops/fetch_job_id.py)
        echo "job_id=${JOB_ID}" >> $GITHUB_OUTPUT

    - name: Collect sys stats
      id: collect_stats
      shell: bash
      env:
        TARGET_OS: ${{ inputs.target_os }}
        TARGET_ARCH: ${{ inputs.target_arch }}
        CXX_COMPILER: ${{ inputs.cxx_compiler }}
        BUILD_CONFIG: ${{ inputs.build_config }}
        STATS_FILE: "RunnerSysStats-${{ steps.fetch_job_id.outputs.job_id }}.json"
      run: |
        eval $(python3 scripts/devops/collect_runner_sys_stats.py)
        echo "cpu_count=${CPU_COUNT}" >> $GITHUB_OUTPUT
        echo "ram_amount_mb=${RAM_AMOUNT}" >> $GITHUB_OUTPUT
        cat << EOF | tee ${STATS_FILE}
        {
          "target_os": "${TARGET_OS}",
          "target_arch": "${TARGET_ARCH}",
          "compiler": "${COMPILER_ID}",
          "build_config": "$(echo ${BUILD_CONFIG} | tr '[:upper:]' '[:lower:]')",
          "cpu_count": ${CPU_COUNT},
          "ram_mb": ${RAM_AMOUNT}
        }
        EOF

    - name: Upload sys stats
      uses: actions/upload-artifact@v4
      with:
        name: RunnerSysStats-${{ steps.fetch_job_id.outputs.job_id }}
        path: RunnerSysStats-${{ steps.fetch_job_id.outputs.job_id }}.json
        retention-days: 1
