#!/usr/bin/env python3
"""Assemble mrbind-generated Python-binding sources into a tree an external
compiler (MSVC) can build, without going through generate.mk's clang command line.

`scripts/mrbind/generate.mk` normally both *generates* (parses with libclang) and
*compiles+links* (with clang) the Python bindings. To instead build them with MSVC
(see source/mrmeshpy/{mrmeshpy.vcxproj,CMakeLists.txt}), we run only the parser
(`make ... only-generate`) and then run this script to lay out a self-contained
source tree:

    <out>/generated/<module>.generated.cpp          # the big parsed binding source (not compiled directly)
    <out>/generated/<module>.helpers.generated.cpp   # parsed helpers
    <out>/generated/aliases.cpp                       # copied verbatim (compiled as-is by generate.mk too)
    <out>/src/mrbind_config.h                          # the -D defines generate.mk passes to the compiler
    <out>/src/<module>.fragment.<k>.cpp  (k=0..N-1)    # one TU per fragment, #includes the big source
    <out>/src/<module>.helpers.cpp                     # wrapper TU for the helpers
    <out>/src/aliases.cpp                              # wrapper TU for aliases

The fragment wrappers reproduce generate.mk's per-fragment compile: the same generated
file is compiled N times with different MB_FRAGMENT / MB_NUM_FRAGMENTS, fragment 0 also
getting MB_DEFINE_IMPLEMENTATION. Only the wrappers (+ helpers + aliases) live under src/
so a `src/**/*.cpp` glob in the project file compiles exactly those.

The parser always runs under libclang regardless of this; only the compile/link changes.
"""

import argparse
import pathlib
import shutil
import sys

# The -D defines generate.mk passes to the bindings compiler that are NOT already provided by
# source/common.props. These mirror scripts/mrbind/compiler_only_flags.txt and the Python-only
# additions in generate.mk (MR_COMPILING_*, PYBIND11_INTERNALS_VERSION, MB_PB11_MODULE_NAME).
# Keep in sync with those if they change. Py_LIMITED_API / PYBIND11_NONLIMITEDAPI_LIB_SUFFIX_FOR_MODULE
# come from common.props on Windows, so they are intentionally not repeated here.
CONFIG_HEADER_TEMPLATE = r'''#pragma once
// Auto-generated by scripts/mrbind/assemble_pybind_msvc.py. Do not edit.
// Mirrors the -D flags scripts/mrbind/generate.mk passes to the bindings compiler
// (compiler_only_flags.txt + the Python additions), so the generated bindings can be
// compiled by MSVC without that makefile's clang command line.
#define MRBIND_HEADER "mrbind_target_pybind11.h"
#define MB_PB11_ADJUST_NAMES "s/\\bMR:://g"
#define MB_PB11_STRIPPED_NAMESPACES "MR","MR.Extra","MR.Cuda"
// The flag-style macros below are passed by generate.mk as `-DFOO`, which the compiler defines to 1.
// They MUST be defined to 1 here (not value-less): core.h tests them with `#if FOO`, and an empty
// macro makes that `#if` ill-formed (MSVC C1017: invalid integer constant expression).
#define MB_PB11_ENABLE_CXX_STYLE_CONTAINER_METHODS 1
#define MB_PB11_MERGE_STL_TL_EXPECTED 1
#define MB_PB11_NO_REGISTER_TYPE_DEPS 1
#define MR_COMPILING_ANY_BINDINGS 1
#define MR_COMPILING_PB11_BINDINGS 1
#define PYBIND11_INTERNALS_VERSION 5
#define MB_PB11_MODULE_NAME {module_pyname}
'''


def write(path: pathlib.Path, text: str) -> None:
    path.write_text(text, encoding="utf-8")
    print(f"  wrote {path}")


def main() -> int:
    here = pathlib.Path(__file__).resolve().parent
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--temp", required=True, type=pathlib.Path,
                    help="generate.mk TEMP_OUTPUT_DIR with the parsed sources "
                         "(e.g. source/TempOutput/Bindings_python/x64/Release)")
    ap.add_argument("--out", required=True, type=pathlib.Path,
                    help="output project dir (e.g. source/mrmeshpy)")
    ap.add_argument("--module", default="mrmesh", help="mrbind module name (default: mrmesh)")
    ap.add_argument("--pyname", default="mrmeshpy", help="Python module name (default: mrmeshpy)")
    ap.add_argument("--fragments", type=int, required=True,
                    help="number of fragments to split the generated source into")
    args = ap.parse_args()

    if args.fragments < 1:
        ap.error("--fragments must be >= 1")

    temp = args.temp.resolve()
    out = args.out.resolve()
    gen_dir = out / "generated"
    src_dir = out / "src"

    generated = temp / f"{args.module}.generated.cpp"
    helpers_generated = temp / f"{args.module}.extra.helpers.cpp"
    aliases = here / "aliases.cpp"

    if not generated.is_file():
        print(f"error: generated source not found: {generated}\n"
              f"  run `make -f scripts/mrbind/generate.mk only-generate ...` first", file=sys.stderr)
        return 1

    # Start each run from a clean tree so stale fragments from a previous run (e.g. a different
    # fragment count) don't linger and get compiled.
    for d in (gen_dir, src_dir):
        if d.exists():
            shutil.rmtree(d)
        d.mkdir(parents=True)

    print("Copying parsed sources:")
    shutil.copyfile(generated, gen_dir / f"{args.module}.generated.cpp")
    print(f"  {generated} -> {gen_dir / (args.module + '.generated.cpp')}")
    have_helpers = helpers_generated.is_file()
    if have_helpers:
        shutil.copyfile(helpers_generated, gen_dir / f"{args.module}.helpers.generated.cpp")
        print(f"  {helpers_generated} -> {gen_dir / (args.module + '.helpers.generated.cpp')}")
    else:
        print(f"  note: no helpers source at {helpers_generated}, skipping")
    shutil.copyfile(aliases, gen_dir / "aliases.cpp")
    print(f"  {aliases} -> {gen_dir / 'aliases.cpp'}")

    print("Writing build sources:")
    write(src_dir / "mrbind_config.h", CONFIG_HEADER_TEMPLATE.format(module_pyname=args.pyname))

    for k in range(args.fragments):
        # `=1`, not value-less: core.h tests it with `#if MB_DEFINE_IMPLEMENTATION`, and an empty
        # macro makes that `#if` ill-formed (matches the makefile's command-line `-DMB_DEFINE_IMPLEMENTATION`).
        impl = "#define MB_DEFINE_IMPLEMENTATION 1\n" if k == 0 else ""
        write(src_dir / f"{args.module}.fragment.{k}.cpp",
              '// Auto-generated fragment wrapper. Do not edit.\n'
              '#include "mrbind_config.h"\n'
              f"#define MB_NUM_FRAGMENTS {args.fragments}\n"
              f"#define MB_FRAGMENT {k}\n"
              f"{impl}"
              f'#include "../generated/{args.module}.generated.cpp"\n')

    if have_helpers:
        write(src_dir / f"{args.module}.helpers.cpp",
              '// Auto-generated helpers wrapper. Do not edit.\n'
              '#include "mrbind_config.h"\n'
              f'#include "../generated/{args.module}.helpers.generated.cpp"\n')

    write(src_dir / "aliases.cpp",
          '// Auto-generated aliases wrapper. Do not edit.\n'
          '#include "mrbind_config.h"\n'
          '#include "../generated/aliases.cpp"\n')

    print(f"Done: {args.fragments} fragment(s) in {src_dir}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
