#!/bin/bash
set -eo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

export MR_EMSCRIPTEN=ON
export MR_EMSCRIPTEN_SINGLETHREAD="${MR_EMSCRIPTEN_SINGLETHREAD:-1}"
export MESHLIB_BUILD_RELEASE="${MESHLIB_BUILD_RELEASE:-ON}"
export MESHLIB_BUILD_DEBUG="${MESHLIB_BUILD_DEBUG:-OFF}"

exec "${SCRIPT_DIR}/build_source.sh" \
  -D MESHLIB_BUILD_MRVIEWER=OFF \
  -D MESHLIB_BUILD_MESHVIEWER=OFF \
  -D MESHLIB_BUILD_WASM_MODULE=ON \
  -D MESHLIB_BUILD_EXTRA_IO_FORMATS=OFF \
  -D MESHLIB_BUILD_SYMBOLMESH=OFF \
  -D MESHLIB_BUILD_VOXELS=ON \
  -D BUILD_TESTING=OFF \
  -D MESHLIB_WASM_MODULE_TARGET=${MESHLIB_WASM_MODULE_TARGET:-node} \
  "$@"
