function(find_vcpkg_root)
    IF(NOT DEFINED VCPKG_ROOT)
        IF(WIN32)
            set(VCPKG_PATH_FILE "$ENV{LOCALAPPDATA}/vcpkg/vcpkg.path.txt")
        ELSE()
            set(VCPKG_PATH_FILE "$ENV{HOME}/.vcpkg/vcpkg.path.txt")
        ENDIF()
        IF(EXISTS ${VCPKG_PATH_FILE})
            file(READ ${VCPKG_PATH_FILE} VCPKG_ROOT)
            set(VCPKG_ROOT ${VCPKG_ROOT} PARENT_SCOPE)
            IF(DEFINED ENV{VCPKG_ROOT})
                message(WARNING "vcpkg integration file precedes the VCPKG_ROOT environment variable. To override this, set the VCPKG_ROOT CMake variable")
            ENDIF()
        ELSEIF(DEFINED ENV{VCPKG_ROOT})
            set(VCPKG_ROOT $ENV{VCPKG_ROOT} PARENT_SCOPE)
        ENDIF()
    ENDIF()
endfunction()

function(detect_vcpkg_target_triplet)
    cmake_host_system_information(RESULT OS QUERY OS_NAME)
    cmake_host_system_information(RESULT ARCH QUERY OS_PLATFORM)
    string(TOLOWER ${OS} OS)
    string(TOLOWER ${ARCH} ARCH)
    # cast to the vcpkg naming convention
    if(OS STREQUAL "macos")
        set(OS "osx")
    endif()
    if(ARCH STREQUAL "x86_64" OR ARCH STREQUAL "amd64")
        set(ARCH "x64")
    elseif(ARCH STREQUAL "aarch64")
        set(ARCH "arm64")
    endif()
    set(VCPKG_TARGET_TRIPLET "${ARCH}-${OS}-meshlib" CACHE STRING "vcpkg target triplet")
endfunction()

IF(WIN32)
    set(MESHLIB_USE_VCPKG_DEFAULT ON)
ELSE()
    set(MESHLIB_USE_VCPKG_DEFAULT OFF)
ENDIF()
option(MESHLIB_USE_VCPKG "Use the vcpkg package manager" ${MESHLIB_USE_VCPKG_DEFAULT})
IF(MESHLIB_USE_VCPKG)
    IF(NOT DEFINED CMAKE_TOOLCHAIN_FILE)
        find_vcpkg_root()
        IF(DEFINED VCPKG_ROOT)
            message(STATUS "Found vcpkg: ${VCPKG_ROOT}")
            set(CMAKE_TOOLCHAIN_FILE "${VCPKG_ROOT}/scripts/buildsystems/vcpkg.cmake" CACHE PATH "CMake toolchain file")
        ELSE()
            message(FATAL_ERROR "vcpkg not found")
        ENDIF()
    ENDIF()

    IF(NOT DEFINED VCPKG_TARGET_TRIPLET)
        detect_vcpkg_target_triplet()
    ENDIF()
    message(STATUS "Using vcpkg triplet: ${VCPKG_TARGET_TRIPLET}")

    if(VCPKG_MANIFEST_MODE)
        # don't (re-)build dependencies
        set(VCPKG_MANIFEST_INSTALL OFF)
        if(NOT DEFINED VCPKG_MANIFEST_DIR)
            set(VCPKG_MANIFEST_DIR "${CMAKE_CURRENT_LIST_DIR}/../../thirdparty/vcpkg")
        endif()
        if(NOT DEFINED VCPKG_INSTALLED_DIR)
            if(DEFINED ENV{VCPKG_INSTALLED_DIR})
                # intended for CI only; set the CMake variable explicitly in your environment
                set(VCPKG_INSTALLED_DIR $ENV{VCPKG_INSTALLED_DIR})
            else()
                set(VCPKG_INSTALLED_DIR "${PROJECT_ROOT_DIR}/vcpkg_installed")
            endif()
        endif()
        message(STATUS "Manifest mode enabled, binaries' location: ${VCPKG_INSTALLED_DIR}")
    endif()
ELSEIF(MESHLIB_USE_VCPKG_DEFAULT)
    message(WARNING "vcpkg is disabled explicitly")
ENDIF()
