set(CMAKE_CXX_STANDARD ${MR_CXX_STANDARD})
set(CMAKE_CXX_STANDARD_REQUIRED ON)

set(CMAKE_HIP_STANDARD 20)
set(CMAKE_HIP_STANDARD_REQUIRED ON)

if(NOT DEFINED CMAKE_HIP_ARCHITECTURES)
  execute_process(
    COMMAND rocm_agent_enumerator
    OUTPUT_VARIABLE CMAKE_HIP_ARCHITECTURES
    OUTPUT_STRIP_TRAILING_WHITESPACE
  )
endif()

find_package(HIP REQUIRED)
