option(MESHLIB_DISABLE_VCPKG "Disable the vcpkg package manager" OFF)
IF(NOT DEFINED CMAKE_TOOLCHAIN_FILE AND NOT MESHLIB_DISABLE_VCPKG)
    IF(DEFINED ENV{VCPKG_ROOT})
        set(CMAKE_TOOLCHAIN_FILE "$ENV{VCPKG_ROOT}/scripts/buildsystems/vcpkg.cmake")
    ELSE()
        IF(WIN32)
            set(VCPKG_PATH_FILE "$ENV{LOCALAPPDATA}/vcpkg/vcpkg.path.txt")
        ELSE()
            set(VCPKG_PATH_FILE "$ENV{HOME}/.vcpkg/vcpkg.path.txt")
        ENDIF()
        IF(EXISTS ${VCPKG_PATH_FILE})
            file(READ ${VCPKG_PATH_FILE} VCPKG_ROOT)
            set(CMAKE_TOOLCHAIN_FILE "${VCPKG_ROOT}/scripts/buildsystems/vcpkg.cmake")
        ENDIF()
    ENDIF()
ENDIF()

IF(WIN32)
    IF(MESHLIB_DISABLE_VCPKG)
        message(WARNING "vcpkg is disabled explicitly")
    ELSEIF(NOT DEFINED CMAKE_TOOLCHAIN_FILE)
        message(FATAL_ERROR "vcpkg not found")
    ENDIF()

    IF(NOT DEFINED VCPKG_TARGET_TRIPLET)
        set(VCPKG_TARGET_TRIPLET "x64-windows-meshlib")
    ENDIF()
ELSE()
    # TODO: triplet for Linux and macOS
ENDIF()
