FUNCTION(mr_emscripten_pack_directory SRC DST)
  set(PRELOAD_ARGUMENTS "--preload-file ${SRC}@${DST} ")
  string(FIND ${CMAKE_EXE_LINKER_FLAGS} ${PRELOAD_ARGUMENTS} FOUND)
  IF(FOUND EQUAL -1)
    set(CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} ${PRELOAD_ARGUMENTS}" PARENT_SCOPE)
  ENDIF()
ENDFUNCTION()

FUNCTION(mr_emscripten_set_async_func_list FUNC_LIST_FILE)
  set(CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} -s ASYNCIFY_IGNORE_INDIRECT -s  ASYNCIFY_ADD=@${FUNC_LIST_FILE}" PARENT_SCOPE)
ENDFUNCTION()

# Drop a compile option that a subproject forced on its own targets, e.g. oneTBB's -fexceptions
FUNCTION(mr_emscripten_remove_compile_option OPTION)
  FOREACH(target ${ARGN})
    IF(TARGET ${target})
      get_target_property(options ${target} COMPILE_OPTIONS)
      IF(options)
        list(REMOVE_ITEM options ${OPTION})
        set_target_properties(${target} PROPERTIES COMPILE_OPTIONS "${options}")
      ENDIF()
    ENDIF()
  ENDFOREACH()
ENDFUNCTION()
