function(mr_emscripten_pack_directory SRC DST)
  set(PRELOAD_ARGUMENTS "--preload-file ${SRC}@${DST} ")
  string(FIND ${CMAKE_EXE_LINKER_FLAGS} ${PRELOAD_ARGUMENTS} FOUND)
  IF(FOUND EQUAL -1)
    set(CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} ${PRELOAD_ARGUMENTS}")
  ENDIF()
endfunction()
