name: Docker images

on:
  # Triggers the workflow only when a push affects specific files
  push:
    branches: [ master ]
    paths:
      - '.github/workflows/docker-images.yml'
      - 'docker/**'
      - 'requirements/**'
      - 'scripts/**'
      - 'thirdparty/**'
  pull_request:
    branches: [ master ]
    paths:
      - '.github/workflows/docker-images.yml'
      - 'docker/**'
      - 'requirements/**'
      - 'scripts/**'
      - 'thirdparty/**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  image-build-test-upload:
    needs: [ windows-build-test, ubuntu-build-test, fedora-build-test ]
    timeout-minutes: 30
    runs-on: ubuntu-latest
    strategy:
      matrix:
        distribution: [ ubuntu, fedora]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: meshrus
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: docker/${{matrix.distribution}}Dockerfile
          load: true
          tags: meshrus/meshlib-${{matrix.distribution}}:latest