name: Docker images

on:
  workflow_call:
    secrets:
      BUILD_MACHINE_TOKEN:
        required: true
      DOCKERHUB_TOKEN:
        required: true
    outputs:
      image_tag:
        description: "image for testing"
        value: ${{ jobs.image-build-upload.outputs.image_tag }}

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  image-build-upload:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    outputs:
      image_tag: ${{ steps.select-tag.outputs.image_tag}}
    strategy:
      matrix:
        distribution: [ubuntu, fedora]
    steps:
      - name: Filter paths
        uses: dorny/paths-filter@v2
        id: changes
        with:
          token: ${{ secrets.BUILD_MACHINE_TOKEN }}
          filters: |
            src:
              - '.github/workflows/docker-images.yml'
              - 'docker/**'
              - 'requirements/**'
              - 'scripts/**'
              - 'thirdparty/**'

      - name: Select image tag
        id: select-tag
        run: |
          echo "::set-output image_tag=$([ ${{steps.changes.outputs.src}} == 'true' ] && [ ${{github.event_name}} != 'push' ] && echo "${GITHUB_REF##*/}" || echo "latest")"

      - name: Checkout
        if: steps.changes.outputs.src == 'true'
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Set up Docker Buildx
        if: steps.changes.outputs.src == 'true'
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        if: steps.changes.outputs.src == 'true'
        uses: docker/login-action@v1
        with:
          username: meshrus
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        if: steps.changes.outputs.src == 'true'
        uses: docker/build-push-action@v2
        with:
          context: .
          file: docker/${{matrix.distribution}}Dockerfile
          push: true
          tags: meshrus/meshlib-${{matrix.distribution}}:${{steps.select-tag.outputs.image_tag}}
