name: Build and test Ubuntu x64

on:
  workflow_call:
    inputs:
      docker_image_tag:
        required: true
        type: string

jobs:
  generate-c-bindings:
    timeout-minutes: 60
    runs-on: ubuntu-24.04-arm
    permissions:
      contents: read  # This is required for actions/checkout
    container:
      image: meshlib/meshlib-emscripten-c-bindings-arm64:${{inputs.docker_image_tag}}
      options: --user root

    steps:
      - name: Fix git permissions
        run: |
          git config --global --add safe.directory '*'

      - name: Checkout
        uses: actions/checkout@v7

      - name: Checkout third-party submodules
        run: |
          # have to checkout selective submodules by our own
          # related issue: https://github.com/actions/checkout/issues/1779
          # Retried via retry.sh: submodule endpoints occasionally 500.
          bash scripts/retry.sh -- git submodule update --init --depth 1 \
            thirdparty/imgui \
            thirdparty/eigen \
            thirdparty/parallel-hashmap \
            thirdparty/mrbind-pybind11 \
            thirdparty/mrbind \
            thirdparty/expected \
            thirdparty/jsoncpp \
            thirdparty/onetbb \
            thirdparty/openvdb/v10/openvdb \
            thirdparty/spdlog

      - name: Download and unpack MRBind
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          MRBIND_VERSION=$(cat scripts/mrbind/mrbind_version.txt | xargs)
          curl -sL https://github.com/cli/cli/releases/download/v2.95.0/gh_2.95.0_linux_arm64.tar.gz | tar xz
          gh_2.95.0_linux_arm64/bin/gh release download $MRBIND_VERSION \
            --repo MeshInspector/mrbind \
            --pattern "mrbind-linux-$(uname -m).zip"
          unzip "mrbind-linux-$(uname -m).zip"
          mv mrbind thirdparty/mrbind/build

        # We're not using the host headers here because it's more important to check that the normal way of building the bindings (i.e. using Emscripten headers) works,
        #   because you can do this on every OS, as opposed to using host headers, which only works on Linux x64.
      - name: Generate C bindings
        # I get `sh` by default.
        shell: bash
        run: |
          make -f scripts/mrbind/generate.mk TARGET=c -B --trace EM_USE_HOST_HEADERS=0 ENABLE_CUDA=1 CLANG_RESOURCE_DIR=thirdparty/mrbind/build/resource-dir

      - name: Upload C bindings
        uses: actions/upload-artifact@v7
        with:
          name: CBindings
          path: |
            ./source/MeshLibC2
            ./source/MeshLibC2Cuda
          retention-days: 1
