name: Prepare images

on:
  workflow_call:
    inputs:
      docker_image_tag:
        required: true
        type: string
      need_linux_image_rebuild:
        required: true
        type: boolean
      need_linux_vcpkg_rebuild:
        required: true
        type: boolean
      need_windows_vcpkg_rebuild:
        required: true
        type: boolean
      vcpkg_docker_image_tag:
        required: true
        type: string
      vs19_vcpkg_version:
        required: true
        type: string
      vs22_vcpkg_version:
        required: true
        type: string

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  always-success:
    runs-on: aws-micro
    steps:
      - name: Do nothing
        run: echo

  windows-vcpkg-build-upload:
    if: ${{ inputs.need_windows_vcpkg_rebuild }}
    timeout-minutes: 240
    runs-on: ${{ matrix.runner }}
    strategy:
      fail-fast: false
      matrix:
        vs: [ vs2019, vs2022 ]
        include:
          - vs: vs2022
            runner: windows-2025
            vcpkg-version: ${{ inputs.vs22_vcpkg_version }}
            vcpkg_triplet: x64-windows-meshlib
          - vs: vs2019
            runner: windows-2025
            vcpkg-version: ${{ inputs.vs19_vcpkg_version }}
            vcpkg_triplet: x64-windows-meshlib-iterator-debug
    steps:
      - name: Setup vcpkg
        working-directory: C:\vcpkg
        run: |
          git fetch
          git checkout ${{ matrix.vcpkg-version }}
          bootstrap-vcpkg.bat
          vcpkg.exe integrate install

      - name: Checkout
        uses: actions/checkout@v6
        with:
          submodules: true

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@4ce2bbcf5d401e557e0537d863a6aced08605794 # v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Build and cache vcpkg
        env:
          VCPKG_DEFAULT_TRIPLET: ${{ matrix.vcpkg_triplet || 'x64-windows-meshlib' }}
        run: |
          .\thirdparty\install.bat --write-s3 --use-s3-asset-provider
