name: Python Linting
on:
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: psf/black@stable
        with:
          options: "--check"
          src: "./test_python"
          version: "22.10.0"
      - uses: isort/isort-action@master
        with:
          isort-version: "5.12.0"
          sort-paths: "./test_python"
          configuration: "--profile black"