name: Update Release Body

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Release Tag (optional)'
        required: false

  release:
    types:
      - released

permissions:
  contents: write

jobs:
  update-release-body:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Set release tag
        id: set_tag
        run: echo "my_tag=${{ inputs.tag || github.event.release.tag_name }}" >> $GITHUB_OUTPUT

      - name: Setup Release Table
        run: |
          cp scripts/devops/release_table.txt .
          pattern_path="RELEASE_PATH"
          path_repl="https://github.com/MeshInspector/Meshlib/releases/download/SHORT_VERSION"
          pattern_version='SHORT_VERSION'
          version_repl='${{steps.set_tag.outputs.my_tag}}'
          sed -i "s|${pattern_path}|${path_repl}|g" release_table.txt
          sed -i "s|${pattern_version}|${version_repl}|g" release_table.txt

      - name: Upload New Release Body
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          original_release_body=$(gh release view "${{ steps.set_tag.outputs.my_tag }}" --json body -q '.body')
          release_table=$(cat release_table.txt)
          updated_release_body="${original_release_body//%details_after_publish%/$release_table}"
          echo "${updated_release_body}" > updated_release_body.txt
          gh release edit ${{ steps.set_tag.outputs.my_tag }} --notes-file updated_release_body.txt
