name: Test Building Pip Wheels

# This is used to conditionally run `pip-build.yml` in pull requests, if they have the `test-pip-build` label.
# We need a separate file for this to be able to apply a single condition to the whole `pip-build.yml`. Otherwise,
#   if we apply it individually to each job, we get ~11 "job skipped" indicators on every PR, which sucks.

on:
  pull_request:
    branches: [ master ]

jobs:
  test-pip-build:
    if: ${{ contains(github.event.pull_request.labels.*.name, 'test-pip-build') }}
    uses: ./.github/workflows/pip-build.yml
